services:
  api:
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    build: .
    secrets:
      - db-password
    ports:
      - "8000:8000"
    environment:
      DB_PASS_FILE: /run/secrets/db-password
      DJANGO_SUPERUSER_PASSWORD: superuser-password
      DB_HOST: postgres
    entrypoint: /app/entrypoint.sh
    develop:
      watch:
        - action: sync
          path: .
          target: /app
  postgres:
   image: postgres
   restart: always
   user: postgres
   secrets:
     - db-password
   volumes:
     - db-data:/var/lib/postgresql/data
   environment:
     POSTGRES_USER: postgres
     POSTGRES_DB: blogs
     POSTGRES_PASSWORD_FILE: /run/secrets/db-password
   expose:
     - 5432
   healthcheck:
     test: [ "CMD", "pg_isready" ]
     interval: 10s
     timeout: 5s
     retries: 5
volumes:
 db-data:
   name: blog-db-data-local-env
secrets:
 db-password:
   file: secrets/password.txt
